
id = "baltdev.Nightlight"
name = "Daylight"
description = "Supplementary mod for DayAndNight that adds more accurate lighting."
version = "1.1.0"
homepage = "https://github.com/balt-dev/Nightlight"
author = "baltdev"

icon = "icon.png"
readme = "README.md"

[project]
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"

[[dependencies]]
id = "TackleBox"
thunderstore_version = "PuppyGirl-TackleBox-0.5.2"

[[dependencies]]
id = "nubz4lif.daynightcycle"
thunderstore_version = "nubz4lif-DayAndNight-1.0.7"
